### ISSUE TITLE
Use better image scaling algorithms

### ISSUE THREAD

**Issue by mercury233** [IceYGO/ygopro#1]
When the windows is resized, card images was sacled with a simple algorithm, this make it has bad quality. Can you use a better scaling algorithm?

For example, Original pic:
![image](https://cloud.githubusercontent.com/assets/13391795/10930194/fb7c8240-82f6-11e5-9a3a-0c101f0fad57.png)

In game:
![image](https://cloud.githubusercontent.com/assets/13391795/10930160/9b5359e8-82f6-11e5-9e35-e9fa27e6e129.png)

I want:
![image](https://cloud.githubusercontent.com/assets/13391795/10930253/8efd1624-82f7-11e5-9335-e0571292fe3f.png)

**Comment by IceYGO** [comment]
The re-sizing is done by irrlicht, which is using OpenGL or DirectX internally. I do not know if I can easily change the algorithm used by those libraries, but I will check it out..

**Comment by mercury233** [comment]
https://github.com/Fluorohydride/ygopro/pull/2027
